E_SHOPPING/E_SHOPPING/app/urls.py
from django.urls import path
from .views import *
from app import views

app_name = 'home'


urlpatterns = [
        path('', views.loginFunction,name='login'),
        path('reg/', views.Reg,name='reg'),
        path('productlist/', views.Productlist,name='productlist'),
        path('logout/',logoutView,name='logout'),
        path('addproduct/',addproduct,name='addproduct'),
        path('save_product/',Saveproduct,name='save_product'),
        path('editproduct/<str:id>',Editproduct,name='editproduct'),
        path('deleteproduct/<str:id>',DeleteProduct,name='deleteproduct'),
        path('updated/',updated,name='updated'),



]

E_SHOPPING/E_SHOPPING/myweb/urls.py
from django.contrib import admin
from django.urls import path,include
from myweb import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls', namespace='home')),
    path('web/',include('userapp.urls'))
]
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

E_SHOPPING/E_SHOPPING/app/templates/addproduct.html
{% extends 'base.html' %} 
{% load static %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldVuhTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

<style>
  body {
    background-size: 100% 100%;
    background-color: darkslategray;
  }
</style>

{% block content %}

<section class="vh-100 bg-image">
  <div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px; margin: 5%">
            <div class="card-body p-5">
              <h2 class="text-uppercase text-center mb-5">Add product</h2>
              <form method="post" action="{% url 'home:save_product' %}" enctype="multipart/form-data">
                {% csrf_token %}
                {{ forms }}
                <div class="d-flex justify-content-center">
                  <button type="submit" class="btn btn-success btn-block btn-lg">
                    Add
                  </button>
                </div>
              </form>
              {% if form.errors %}
              <div class="alert alert-danger mt-3">
                <ul>
                  {% for field, errors in form.errors.items %}
                    <li>{{ field }}: {{ errors }}</li>
                  {% endfor %}
                </ul>
              </div>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

E_SHOPPING/E_SHOPPING/app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    {% comment %} bootstrap design {% endcomment %}
    <!-- CSS only -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <!-- JavaScript Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'img/favicon.ico' %}"
    />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />

    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
    />

    <style>
      body {
        font-family: "Lato", sans-serif;
        background-color: #f6f7f7 !important;
      }

      .sidenav {
        height: 100%;
        width: 200px;
        position: fixed;
        z-index: 1;
        top: 0;
        left: 0;
        /* background-color: #23384E; */
        background-color: #19242d;
        overflow-x: hidden;
        padding-top: 20px;
        /* border-radius: 2%; */
      }
      h2 {
        color: black;
      }

      .sidenav a {
        padding: 6px 6px 6px 50px;
        text-decoration: none;
        font-size: 25px;
        color: #818181;
        display: block;
      }

      .sidenav a:hover {
        /* color: #f1f1f1; */
        background-color: #134f5e;
        color: #079eb7;
        text-decoration: none;
      }

      #base_h1 {
        font-family: Georgia, sans-serif;
        font-size: 4.5em;
        letter-spacing: -2px;
        color: black;
        margin-left: 0%;
        margin-top: -10%;
        margin-bottom: 18%;
        background-color: white;
        /* border-radius: 0% 0% 10% 10%; */
        border-radius: 0% 0% 15% 7%;
        text-align: center;
      }
      #admin_head {
        font-family: "Trebuchet MS", sans-serif;
        font-size: 3em;
        letter-spacing: -2px;
        border-bottom: 2px solid black;
        text-transform: uppercase;
      }

      /* mobile view */

      /* @media screen and (max-width: 700px) {
    .sidenav {
      width: 100%;
      height: auto;
      position: relative;

    }
    #base_h1{
        text-align: center;
    }
    .sidenav a {float: left;}
    div.content {margin-left: 0;}
  }
  
  @media screen and (max-width: 600px) {
    .sidenav a {
      text-align: center;
      float: none;
    }
  } */
    </style>

    {% comment %} top navbar {% endcomment %}

    <style>


      #navbar {
        overflow: hidden;
        background-color: #19242D;
      }


      #navbar a {
        float: left;
        display: block;
        color: #f2f2f2;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
        font-size: 17px;
      }

      #navbar a:hover {
        background-color: #ddd;
        color: black;
      }

      #navbar a.active {
        background-color: #079EB7;
        color: white;
      }
      .topnav-right {
        float: right;
      }

      .content {
        padding: 16px;
      }

      .sticky {
        {% comment %} position: fixed; {% endcomment %}
        position: sticky;
        top: 0;
        width: 100%;
      }

      .sticky + .content {
        padding-top: 60px;
      }
    </style>
  </head>

  <body>
    <div id="navbar">
      <div class="topnav-right">
        <a href="{% url 'home:logout' %}">logout</a>
      </div>
    </div>

    <div class="main">{% block content %} {% endblock %}</div>

    <script>
      window.onscroll = function () {
        myFunction();
      };

      var navbar = document.getElementById("navbar");
      var sticky = navbar.offsetTop;

      function myFunction() {
        if (window.pageYOffset >= sticky) {
          navbar.classList.add("sticky");
        } else {
          navbar.classList.remove("sticky");
        }
      }
    </script>
  </body>
</html>

E_SHOPPING/E_SHOPPING/app/templates/electronics.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Products</title>
  </head>
  <body>
    <div class="container">
        <div class="row justify-content-center my-3">
            <div class="col-auto">
                <a href="{% url 'home:addproduct' %}" class="btn btn-primary text-white nav-item nav-link px-3">
                    Add Product
                </a>
            </div>
            <div class="col-auto">
                <a href="{% url 'home:updated' %}" class="btn btn-primary text-white nav-item nav-link px-3">
                    Recently Updated
                </a>
            </div>
        </div>
        <div class="row">
            {% for i in product %}
            <div class="col-lg-3 mb-4">
                <div class="card" style="width: 18rem;">
                    <img src="{{ i.files.url }}" class="card-img-top" alt="...">
                    <div class="card-body">
                      <h5 class="card-title">{{ i.name }}</h5>
                      <p class="card-text">{{ i.product_category }}</p>
                      <p class="card-text">{{ i.highlights }}</p>
                      <p class="card-text">RS:{{ i.price }}</p>
                      <a href="{% url 'home:deleteproduct' i.id %}" class="btn btn-primary">Delete</a>
                      <a href="{% url 'home:editproduct' i.id %}" class="btn btn-primary">Update</a>
                      <input type="hidden" value="{{ i.id }}">
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js

E_SHOPPING/E_SHOPPING/app/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <style>
        body {
            background-color: #f8f9fa;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }
        .login-container {
            background: #fff;
            padding: 2rem;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0,0,0,0.1);
        }
        .img-container {
            background-image: url("{% static 'img/login_bg.jpg' %}");
            background-size: cover;
            background-position: center;
            border-radius: 10px 0 0 10px;
        }
    </style>
</head>
<body>

<section class="container login-container">
    <div class="row justify-content-center">
        <div class="col-md-6 img-container d-none d-md-block"></div>
        <div class="col-md-6 p-5">
            <h1 class="text-center mb-4" id="login_head">Sign In</h1>
            <form method="post" class="signin-form">
                {% csrf_token %}
                {{ form }}
                <div class="form-group">
                    <button type="submit" class="form-control btn btn-primary rounded submit px-3">Sign In</button>
                </div>
                {% if messages %}
                    <div class="mt-3">
                        {% for message in messages %}
                            <div class="alert {{ message.tags }}">{{ message }}</div>
                        {% endfor %}
                    </div>
                {% endif %}
            </form>
            <p class="text-center mt-3">Not a member? <a href="{% url 'home:reg' %}">Sign Up</a></p>
        </div>
    </div>
</section>

</body>
</html>

E_SHOPPING/E_SHOPPING/app/templates/product_edit.html
{% extends 'base.html' %} {% load static %}
<link
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
  rel="stylesheet"
  integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
  crossorigin="anonymous"
/>
<!-- JavaScript Bundle with Popper -->
<script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
  crossorigin="anonymous"
></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

<style>
  body {
    /* background-image: url({% static 'img/reg_bg.jpg' %}); */

    /* background-repeat: no-repeat; */
    background-size: 100% 100%;
    background-color: darkslategray;
  }
</style>

{% block content %}

<section class="vh-100 bg-image">
  <div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px; margin: 5%">
            <div class="card-body p-5">
              <h2 class="text-uppercase text-center mb-5">Update Profile</h2>

              <form method="post" action="" enctype="multipart/form-data">
                {% csrf_token %}
                {{form}}
                <div class="d-flex justify-content-center">
                  <button
                    type="submit"
                    id="submitButton"
                    class="btn btn-success btn-block btn-lg"
                  >
                    Update
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<script
  src="https://code.jquery.com/jquery-3.6.0.min.js"
  integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
  crossorigin="anonymous"
></script>

{% endblock%}

E_SHOPPING/E_SHOPPING/app/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <style>
        body {
            background-color: #f8f9fa;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }
        .register-container {
            background: #fff;
            padding: 2rem;
            border-radius: 15px;
            box-shadow: 0 4px 8px rgba(0,0,0,0.1);
        }
    </style>
</head>
<body>

<section class="vh-100">
  <div class="d-flex align-items-center h-100">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card register-container">
            <div class="card-body p-5">
              <h2 class="text-uppercase text-center mb-5">Create an account</h2>
              <form method="post">
                {% csrf_token %}
                {{ form }}
                <div class="d-flex justify-content-center">
                  <button type="submit" id="submitButton" class="btn btn-success btn-block btn-lg">Register</button>
                </div>
                <p class="text-center text-muted mt-5 mb-0">Have already an account? <a href="{% url 'home:login' %}" class="fw-bold text-body"><u>Login here</u></a></p>
              </form>
              {% if form.errors %}
              <div class="alert alert-danger mt-3">
                <ul>
                  {% for field, errors in form.errors.items %}
                    <li>{{ field }}: {{ errors }}</li>
                  {% endfor %}
                </ul>
              </div>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript">
  $(document).ready(function () {
    $("#confirm_password").on("keyup", function () {
      document.getElementById("submitButton").disabled = true;
      var pass_value = document.getElementById("password").value;
      if (pass_value == "") {
        document.getElementById("submitButton").disabled = true;
      } else {
        if ($("#password").val() == $("#confirm_password").val()) {
          $("#message").html("");
          document.getElementById("submitButton").disabled = false;
        } else {
          $("#message").html("Passwords not matching!").css("color", "red");
        }
      }
    });
  });
</script>

</body>
</html>

E_SHOPPING/E_SHOPPING/app/templates/updatedlist.html
{% extends 'base.html' %} {% load static %} {% block content %}

<style>
  #admin_head{
    font-family: "Trebuchet MS", sans-serif;
    font-size: 3em;
    letter-spacing: -2px;
    border-bottom: 2px solid black;
    text-transform: uppercase;
  }
  div.dataTables_wrapper div.dataTables_length select {
    width: 65px;
    display: inline-block;
    height: 0%;
</style>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="assets/js/bootstrap.min.js"></script>
<script
  type="text/javascript"
  src="https://cdn.datatables.net/v/bs-3.3.7/jq-2.2.4/dt-1.10.13/b-1.2.4/b-html5-1.2.4/b-print-1.2.4/fh-3.1.2/r-2.1.1/sc-1.4.2/datatables.min.js"
></script>

<link href="assets/css/bootstrap.min.css" rel="stylesheet" />
<link href="assets/css/style.css" rel="stylesheet" />
<link
  rel="stylesheet"
  type="text/css"
  href="https://cdn.datatables.net/v/bs-3.3.7/jq-2.2.4/dt-1.10.13/b-1.2.4/b-html5-1.2.4/b-print-1.2.4/fh-3.1.2/r-2.1.1/sc-1.4.2/datatables.min.css"
/>
<h1 id="admin_head">Recently Updated Products</h1>

<table class="table table-striped" id="table_id">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Prodcut Category</th>
      <th scope="col">Price</th>
      <th scope="col">Image</th>
    </tr>
  </thead>
  <tbody>
    {% for i in updated_products %}
    <tr>
      <td scope="row">{{forloop.counter}}</td>
      <td>{{i.name}}</td>
      <td>{{i.prodcut_category}}</td>
      <td>{{i.price}}</td>
      <td> <img src="{{ i.files.url }}" alt="{{ i.name }}" style="max-width: 100px; max-height: 100px;"></td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<script>
  $(document).ready(function () {
    $("#table_id").DataTable();
  });
</script>

{% endblock%}